[package]
name = "helloproofs"
version = "0.1.0"
authors = ["Nozdormu <w1999wtw3537@sina.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
